services:
  pgdatabase:
    image: postgres:17
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"

  data_processor:
    build: .
    depends_on:
      - pgdatabase
    env_file:
      - .env
    volumes:
      - ny_taxi_db_data_volume:/data
    command: ["python", "download_data.py"]

volumes:
  postgres_data:
  ny_taxi_db_data_volume:
